### ISSUE TITLE
Material-ui and react-tap-event-plugin

### ISSUE THREAD

**Issue by rravikot** [thereactivestack/meteor-webpack#135]
There seem to be a lot of issues when Material-ui is involved. I've seen a few threads (#21) on this, but it seems a lot has changed since then (the biggest thing being Meteor 1.3). I just wanted to open up this issue again and get an up-to-date solution. 

I would prefer to just use the `react-tap-event-plugin` like normal, but that doesn't seem to be working because there are two different versions of react (react-runtime and the npm version). I tried to just remove the react-runtime package in hopes of just using the NPM one (as outlined in the instructions), but it leads to #73. 

Here's the error I get when I do use the react-runtime package:
```
TypeError: (0 , _reactAddonsCreateFragment2.default) is not a function
    at Object.create (eval at <anonymous> (web.js:4843), <anonymous>:36:52)
    at render (eval at <anonymous> (web.js:5491), <anonymous>:331:53)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (modules.js?hash=adcdc3e…:10556)
    at ReactCompositeComponentMixin._renderValidatedComponent (modules.js?hash=adcdc3e…:10576)
    at wrapper [as _renderValidatedComponent] (modules.js?hash=adcdc3e…:4334)
    at ReactCompositeComponentMixin.mountComponent (modules.js?hash=adcdc3e…:10189)
    at wrapper [as mountComponent] (modules.js?hash=adcdc3e…:4334)
    at Object.ReactReconciler.mountComponent (modules.js?hash=adcdc3e…:8605)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (modules.js?hash=adcdc3e…:17000)
    at ReactDOMComponent.Mixin._createContentMarkup (modules.js?hash=adcdc3e…:14339)
```

**Comment by yogiben** [comment]
@rravikot please keep this thread updated.

I'll have to abandon webpack for now, unless there's a fix :(

**Comment by rravikot** [comment]
I've had to do the same, unfortunately. I'll definitely check back if I find a good solution.

**Comment by vsheyanov** [comment]
If any one come up with any kind of workaround, please post it, until the issue is fixed.

**Comment by vsheyanov** [comment]
After upgrading react to 15, material-ui to 15(beta) tap event plugin works as expected,

thanks @eXon !

**Comment by eXon** [comment]
Awesome
